title: Ganesh Swami
description: My Portfolio Website
show_downloads: false

photo: /assets/img/myphoto.jpg

# describe text below image
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme